global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']

  - job_name: 'opentelemetry-collector'
    static_configs:
      - targets: ['opentelemetry-collector:8889']

  - job_name: 'my_app_metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:7005']
