services:
  consul:
    image: hashicorp/consul
    container_name: consul
    ports:
      - 8500:8500
      - 8400:8400
      - 8600:8600
      - 8600:8600/udp
    networks:
      - telemetry-network

  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.68.0
    container_name: open_telemetry_collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./tools/telemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"  # gRPC
      - "4318:4318"  # HTTP
      - "8888:8888"  # Prometheus metrics exposed by the collector
      - "8889:8889"  # Prometheus exporter metrics
    networks:
      - telemetry-network

  prometheus:
    image: bitnami/prometheus
    container_name: prometheus
    volumes:
      - ./tools/telemetry/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - telemetry-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./tools/telemetry/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/all.yaml
    ports:
      - 3000:3000
    networks:
      - telemetry-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    networks:
      - telemetry-network

networks:
  telemetry-network:
    driver: bridge
